#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module for cshrc environment variables
# This script simply changes the .cshrc file. Any Csh process created after
# this will see the environment variables which specifies the proxy server to
# be used, or else unset to disable the use of a proxy server. This script
# does not make programs use these settings - some do, some don't, and not all
# programs do so equally well - refer to programs' manual pages for info on
# support for a proxy server

# Two noteworthy programs that does use this info are:
#    Google Earth
#    DropBox client

CSH_CF=$PM_USERHOME/.cshrc
TEMPFILE=/tmp/p0n.cshrc
[ -f $TEMPFILE ] && ( rm $TEMPFILE || exit 3 )

. $PM_INSTALL_DIR/modules/.sharedfunctions

case "$1" in
  on)
    echo Enabling for Csh
    grep -vi "^[^#]*_proxy" $CSH_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/enable_cshrc >> $TEMPFILE
    cp $TEMPFILE $CSH_CF
    echo "    Restart terminal to affect"
    ;;
  off)
    echo Disabling for Csh
    if [ -f $BASSH_CF ]
    then
        grep -vi "^[^#]*_proxy" $CSH_CF > $TEMPFILE
        cat $PM_INSTALL_DIR/templates/disable_cshrc >> $TEMPFILE
        mv $TEMPFILE $CSH_CF
    fi
    echo "    Restart terminal to affect"
    ;;

  check)
    CSH_CHECK=$( [ -f $CSH_CF ] && grep -ci "^[^#]*_proxy=" $CSH_CF 2>/dev/null || CSH_CHECK=None )
    echo Csh: $CSH_CHECK \( http_proxy=\"$http_proxy\" \)
    ;;
esac
