#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module for Curl

# sets Proxy server options for Curl via the Curl .curlrc file in the user's
# home directory

# Existing curl processes needs to be restarted. Typically a new curl process
# is started for each "job" so the next job to start will see the new settings
# at that time.

CURL_CF=$PM_USERHOME/.curlrc
TEMPFILE=/tmp/pon.curlrc
[ -f $TEMPFILE ] && ( rm $TEMPFILE || exit 3 )

case "$1" in
  on)
    echo Enabling for Curl-RC
    [ -f $CURL_CF ] && grep -v "^proxy =" $CURL_CF > $TEMPFILE
    cat $PM_INSTALL_DIR/templates/enable_curl >> $TEMPFILE
    mv $TEMPFILE $CURL_CF
    ;;
  off)
    echo Disabling for Curl-RC
    if [ -f $CURL_CF ] 
    then
        grep -v "^proxy =" $CURL_CF > $TEMPFILE
        mv $TEMPFILE $CURL_CF
    fi
    ;;
  check)
    CURL_CHECK=$(grep -c proxy $CURL_CF 2>/dev/null) || CURL_CHECK=None
    echo Curl-RC: $CURL_CHECK
esac
