#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module for Curl Proxy setting management

# sets Proxy server options for Curl via the Curl .curlrc file in the user's
# home directory

# Existing curl processes needs to be restarted. Typically a new curl process
# is started for each "job" so the next job to start will see the new settings
# at that time.

CURL_CF=$PM_USERHOME/.curlrc
. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile curlrc


case "$1" in
  on)
    echo Enabling for Curl
    if [ -f $CURL_CF ]
    then
       grep -v "^[^#]*proxy =" $CURL_CF > $TEMPFILE
       ParseTemplate $PM_INSTALL_DIR/templates/enable_curl >> $TEMPFILE
       cp $TEMPFILE $CURL_CF
    fi
    ;;
  off)
    echo Disabling for Curl
    if [ -f $CURL_CF ] 
    then
        grep -v "^[^#]*proxy =" $CURL_CF > $TEMPFILE
        cp $TEMPFILE $CURL_CF
    fi
    ;;
  check*)
    if [ ! -f $CURL_CF ]
    then  CURL_CHECK="Not Found"
    elif [ $( grep -c "^[^#]*proxy =" $CURL_CF 2>/dev/null ) -eq 0 ]
      then CURL_CHECK=Off
      else CURL_CHECK=On
    fi
    echo Curl: $CURL_CHECK
esac
