#!/bin/bash
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# This ProxyManager module switches the git user global Proxy setting on or off

GIT_CF=$PM_USERHOME/.gitconfig

. $PM_INSTALL_DIR/modules/.sharedfunctions

case "$1" in
  on)
    echo Enabling for Git global
    which git > /dev/null || exit
    git config --global http.proxy http://${PM_PROXY_HOST}:${PM_PROXY_PORT}
    ;;
  off)
    echo Disabling for Git global
    which git > /dev/null || exit
    git config --global http.proxy ""
    ;;
  check)
    if ! which git > /dev/null
    then GIT_CHECK="Not Found"
    elif [ $( git config --global http.proxy | grep -c http ) -eq 0 ]
       then GIT_CHECK=Off
       else GIT_CHECK=On
    fi
    echo "Git: $GIT_CHECK"
    ;;
esac
