#!/bin/bash
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# This ProxyManager module switches the KDE global Proxy setting on and off for
# compliant application, i.e many if not actually most GTK applications.

# Note I copied the method from somewhere on the web.  Testing is sorely lacking.

case "$1" in
  on)
    echo Enabling for Gnome
    gsettings set org.gnome.system.proxy mode 'manual'
    gsettings set org.gnome.system.proxy.http port $PM_PROXY_PORT
    gsettings set org.gnome.system.proxy.http host $PM_PROXY_HOST
    ;;
  off)
    echo Disabling for Gnome
    gsettings set org.gnome.system.proxy mode 'none'
    ;;
  check)
    echo Gnome: $( gsettings get org.gnome.system.proxy mode  )
    ;;
esac
