#!/bin/bash
# This file is part of ProxyManager
# Copyright 2014 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# This ProxyManager module switches the KDE global Proxy setting on and off for
# compliant applications.

# Note: This module requires the KDE global proxy setting to be manually set 
# once

KDE_CF=$PM_USERHOME/.kde/share/config/kioslaverc
[ -d $PM_USERHOME/.kde4 ] && KDE_CF=$PM_USERHOME/.kde4/share/config/kioslaverc

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile kioslaverc

switch_kde() {
     case "$1" in
     1)
       ParseTemplate $PM_INSTALL_DIR/templates/enable_kde ;;
     0)
       sed -ie "s/ProxyType=./ProxyType=0/" ${KDE_CF} ;;
     esac > $TEMPFILE
     cp $TEMPFILE ${KDE_CF}
     dbus-send --type=signal /KIO/Scheduler org.kde.KIO.Scheduler.reparseSlaveConfiguration string:""
}

case "$1" in
      on)
        echo Enabling for KDE global
        switch_kde 1
        ;;

      off)
        echo Disabling for KDE global
        switch_kde 0
        ;;

      install)
         # This will in future set up the proxy by means of a template
         ParseTemplate $PM_INSTALL_DIR/templates/enable_kde > $TEMPFILE
         cp $TEMPFILE ${KDE_CF}
         ;;

      check)
        if [ ! -f $KDE_CF ]
        then KDE_CHECK="Not Found"
        elif [ $( grep -c ProxyType=1 $KDE_CF 2>/dev/null ) -eq 0 ]
          then KDE_CHECK=Off
          else KDE_CHECK=On
        fi
        echo "KDE: $KDE_CHECK"
        ;;
esac

