#!/bin/sh
# ProxyManager module for Marble Virtual Globe
# This file is part of ProxyManager
# Copyright 2014 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# You need to restart any already running Marble instances.

MARBLE_CF=$PM_USERHOME/.kde*/share/config/marblerc

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile marble

case "$1" in
  on)
    echo Enabling for Marble
    sed '/\[Cache\]/,/^$/ d' $MARBLE_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/enable_marble >> $TEMPFILE
    mv $TEMPFILE $MARBLE_CF
    pgrep -U ${PM_USERNAME} marble >/dev/null && echo "   Restart Marble for changed setting to take effect"
    ;;
  off)
    echo Disabling for Marble
    sed '/\[Cache\]/,/^$/ d' $MARBLE_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/disable_marble >> $TEMPFILE
    mv $TEMPFILE $MARBLE_CF
    pgrep marble >/dev/null && echo "   Restart Marble for changed setting to take effect"
    ;;
  check)
    if [ ! -f $MARBLE_CF ]
    then  MARBLE_CHECK="Not Found"
    elif [ $( grep -c "^proxyUrl=http://.*[a-z]" $MARBLE_CF 2>/dev/null ) -eq 0 ]
       then MARBLE_CHECK=Off
       else MARBLE_CHECK=On
    fi
    echo Marble: $MARBLE_CHECK
    ;;
esac
