#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module for Root user .bashrc profile
# Usefull for some sudo-based jobs, eg apt-add-repository

. /etc/proxymanager.conf
RBASH_CF=~root/.bashrc
TEMPFILE=/tmp/pon.rbash
[ -f $TEMPFILE ] && ( rm $TEMPFILE || exit 3 )

case "$1" in
  on)
    echo Enabling for Root BashRC
    grep -vi "_proxy=" $RBASH_CF > $TEMPFILE
    cat $PM_INSTALL_DIR/templates/enable_bashrc >> $TEMPFILE
    mv $TEMPFILE $RBASH_CF
    ;;
  off)
    echo Disabling for Root BashRC
    if [ -f $RBASH_CF ]
    then
        grep -vi "_proxy=" $RBASH_CF > $TEMPFILE
        mv $TEMPFILE $RBASH_CF
    fi
    ;;
  check)
    RBASH_CHECK=$(grep -ci _proxy $RBASH_CF 2>/dev/null) || RBASH_CHECK=None
    echo Root Bash-RC: $RBASH_CHECK
esac

