#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module for Root user .curlrc profile
# Usefull on Yast based systems (eg OpenSUSE)

. /etc/proxymanager.conf
RCURL_CF=~root/.curlrc
TEMPFILE=/tmp/pon.rcurl
[ -f $TEMPFILE ] && ( rm $TEMPFILE || exit 3 )

. $PM_INSTALL_DIR/modules/.sharedfunctions

case "$1" in
  on)
    echo Enabling for Root Curl \(eg for Yast\)
    grep -v "^[^#]*proxy =" $RCURL_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/enable_curl >> $TEMPFILE
    mv $TEMPFILE $RCURL_CF
    ;;
  off)
    echo Disabling proxy for Root Curl
    if [ -f $RCURL_CF ]
    then
        grep -v "^[^#]*proxy =" $RCURL_CF > $TEMPFILE
        mv $TEMPFILE $RCURL_CF
    fi
    ;;
  check)
    RCURL_CHECK=$( [ -f $RCURL_CF ] && grep -c "^[^#]*proxy =" $RCURL_CF 2>/dev/null || RCURL_CHECK=None )
    echo Root Curl: $RCURL_CHECK
esac

