#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module for cshrc environment variables
# This script simply changes the .cshrc file. Any Csh process created after
# this will see the environment variables which specifies the proxy server to
# be used, or else unset to disable the use of a proxy server. This script
# does not make programs use these settings - some do, some don't, and not all
# programs do so equally well - refer to programs' manual pages for info on
# support for a proxy server

# Two noteworthy programs that does use this info are:
#    Google Earth
#    DropBox client

. /etc/proxymanager.conf
RCSH_CF=~root/.cshrc
. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile root-cshrc


case "$1" in
  on)
    echo Enabling for Root Csh
    grep -vi "^[^#]*_proxy" $RCSH_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/enable_cshrc >> $TEMPFILE
    cp $TEMPFILE $RCSH_CF
    echo "    Restart terminal to affect"
    ;;
  off)
    echo Disabling for Root Csh
    if [ -f $BASSH_CF ]
    then
        grep -vi "^[^#]*_proxy" $RCSH_CF > $TEMPFILE
        cat $PM_INSTALL_DIR/templates/disable_cshrc >> $TEMPFILE
        mv $TEMPFILE $RCSH_CF
    fi
    echo "    Restart terminal to affect"
    ;;

  check)   
    if [ ! -f $RCSH_CF ]
    then RCSH_CHECK="Not Found"
    elif [ $( grep -ci "^[^#]*setenv .*_proxy .*http.*" $RCSH_CF 2>/dev/null ) -eq 0 ]
      then RCSH_CHECK=Off
      else RCSH_CHECK=On
    fi
    echo "Root Csh: $RCSH_CHECK"    
    ;;
esac
