#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module for Root user .bashrc profile
# Usefull for some sudo-based jobs, eg apt-add-repository

. /etc/proxymanager.conf
RBASH_CF=~root/.bashrc
TEMPFILE=/tmp/pon.rbash
[ -f $TEMPFILE ] && ( rm $TEMPFILE || exit 3 )

. $PM_INSTALL_DIR/modules/.sharedfunctions

case "$1" in
  on)
    echo Enabling for Root Bash
    grep -vi "^[^#]*_proxy" $RBASH_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/enable_bashrc >> $TEMPFILE
    mv $TEMPFILE $RBASH_CF
    ;;
  off)
    echo Disabling for Root Bash
    if [ -f $RBASH_CF ]
    then
        grep -vi "^[^#]*_proxy" $RBASH_CF > $TEMPFILE
        cat $PM_INSTALL_DIR/templates/disable_bashrc >> $TEMPFILE
        mv $TEMPFILE $RBASH_CF
    fi
    ;;
  check)
    RBASH_CHECK=$( [ -f $RBASH_CF ] && grep -ci "^[^#]*_proxy=" $RBASH_CF 2>/dev/null || RBASH_CHECK=None )
    echo Root Bash: $RBASH_CHECK
esac

