#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module for Root user .curlrc profile
# Usefull on Yast based systems (eg OpenSUSE)

. /etc/proxymanager.conf
RCURL_CF=~root/.curlrc

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile rootcurl


case "$1" in
  on)
    echo Enabling for Root Curl \(eg for Yast\)
    grep -v "^[^#]*proxy =" $RCURL_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/enable_curl >> $TEMPFILE
    mv $TEMPFILE $RCURL_CF
    ;;
  off)
    echo Disabling proxy for Root Curl
    if [ -f $RCURL_CF ]
    then
        grep -v "^[^#]*proxy =" $RCURL_CF > $TEMPFILE
        mv $TEMPFILE $RCURL_CF
    fi
    ;;
  check*)
    if [ ! -f $RCURL_CF ]
    then  RCURL_CHECK="Not Found"
    elif [ $( grep -c "^[^#]*proxy =" $RCURL_CF 2>/dev/null ) -eq 0 ]
      then RCURL_CHECK=Off
      else RCURL_CHECK=On
    fi
    echo Root Curl: $RCURL_CHECK   
    ;;
esac

