#!/bin/sh
# ProxyManager module for Amazon S3 client S3cmd 
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# Existing s3cmd processes needs to be restarted.

# Note: Official documentation states that s3cmd can not be 
# used with an https proxy.  So it is not supported.  Regardless
# it works just perfectly ... for me.  YMMV

S3CMD_CF=$PM_USERHOME/.s3cfg

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile s3cfg


case "$1" in
  on)
    echo Enabling for S3cmd
    grep -v "^[^#]*proxy_.* =" $S3CMD_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/enable_s3cfg >> $TEMPFILE
    mv $TEMPFILE $S3CMD_CF
    ;;
  off)
    echo Disabling for S3cmd
    grep -v "^[^#]*proxy_.* =" $S3CMD_CF > $TEMPFILE
    cat $PM_INSTALL_DIR/templates/disable_s3cfg >> $TEMPFILE
    mv $TEMPFILE $S3CMD_CF
    ;;
  check)
    if [ ! -f $S3CMD_CF ]
    then  S3CMD_CHECK="Not Found"
    elif [ $( grep -c "^[^#]*proxy_host* =.*[a-z]" $S3CMD_CF 2>/dev/null ) -eq 0 ]
      then S3CMD_CHECK=Off
      else S3CMD_CHECK=On
    fi
    echo S3cmd: $S3CMD_CHECK
    ;;
esac
