#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module to set System-wide proxy for YUM

# Note: Existing yum processes needs to be restarted for this setting be used.
# Note: Yum may use the http_proxy environment variable if set.

# Run with root priv to affect Global System Configuration

. /etc/proxymanager.conf
YUM_CF=/etc/yum.conf

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile yum

case "$1" in
  on)
    echo Enabling for Yum
    [ -f $YUM_CF ] || exit
    ParseTemplate $PM_INSTALL_DIR/templates/enable_yum > $TEMPFILE
    grep -v "[^#]*proxy=" $YUM_CF > $TEMPFILE
    mv $TEMPFILE $YUM_CF
    ;;
  off)
    echo Disabling for Yum
    [ -f $YUM_CF ] || exit
    grep -v "[^#]*proxy=" $YUM_CF > $TEMPFILE
    mv $TEMPFILE $YUM_CF
    ;;
  check*)
    if [ ! -f $YUM_CF ]
    then YUM_CHECK="Not Found"
    elif [ $( cat $YUM_CF | grep -ci "[^#]*proxy=" 2>/dev/null ) -eq 0 ]
       then YUM_CHECK=Off
       else YUM_CHECK=On
    fi
    echo Yum: $YUM_CHECK
    ;;
esac
