#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module to set System-wide Uptream/parent proxy for Polipo
# The Polipo service will be restarted

# Run with root priv to affect Global System Configuration

. /etc/proxymanager.conf
POL_CF=/etc/polipo/config

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile polipo

case "$1" in
  on)
    echo Enabling for Polipo
    [ -f $POL_CF ] || exit
    grep -vi "^[^#].*parentProxy.*=." $POL_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/enable_polipo >> $TEMPFILE
    mv $TEMPFILE $POL_CF
    /etc/init.d/polipo restart
    ;;
  off)
    echo Disabling for Polipo
    [ -f $POL_CF ] || exit
        # CommentLines "parentProxy." <$POL_CF >$TEMPFILE
    sed 's/^[^#]*parentProxy./# &/' $POL_CF > $TEMPFILE
    mv $TEMPFILE $POL_CF
    /etc/init.d/polipo restart
    ;;
  check*)
    if [ ! -d /etc/polipo ]
    then POL_CHECK="Not Found"
    elif [ $( cat $POL_CF | grep -ci "^[^#]*parentproxy *=." 2>/dev/null ) -eq 0 ]
      then POL_CHECK=Off
      else POL_CHECK=On
    fi
    echo Polipo: $POL_CHECK
    ;;
esac
