#!/bin/sh
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# ProxyManager module to set System-wide proxy for YUM

# Note: Existing yum processes needs to be restarted for this setting be used.
# Note: Yum may use the http_proxy environment variable if set.

# Run with root priv to affect Global System Configuration

. /etc/proxymanager.conf
YUM_CF=/etc/yum.conf
TEMPFILE=/tmp/pm.yum

. $PM_INSTALL_DIR/modules/.sharedfunctions

case "$1" in
  on)
    echo Enabling for Yum
    ParseTemplate $PM_INSTALL_DIR/templates/enable_yum > $TEMPFILE
    grep -v "[^#]*proxy=" $YUM_CF > $TEMPFILE
    mv $TEMPFILE $YUM_CF
    ;;
  off)
    echo Disabling for Yum
    grep -v "[^#]*proxy=" $YUM_CF > $TEMPFILE
    mv $TEMPFILE $YUM_CF
    ;;
  check)
    YUM_CHECK=$( [ ! -f $YUM_CF ] && echo N/A || cat $YUM_CF | grep -ci "[^#]*proxy=" 2>/dev/null )
    echo Yum: $YUM_CHECK
    ;;
esac
