#!/bin/sh
# ProxyManager module for system proxy for distributions that use /etc/environment
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# This works for many desktop applications and services but requires logout/login
# Generally requires a restart for most existing processes.

SYSENV_CF=/etc/environment
. /etc/proxymanager.conf

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile sysenv

case "$1" in
  on)
    echo Enabling for Sys Environment Global setting
    if [ -f $SYSENV_CF ]
    then
       grep -vi "^[^#]*_proxy=" $SYSENV_CF > $TEMPFILE
       cat $PM_INSTALL_DIR/templates/enable_environment >> $TEMPFILE
       mv $TEMPFILE $SYSENV_CF
       echo "    Logout and back or restart system may be required"
    fi
    ;;
  off)
    echo Disabling for Sys Environment Global setting
    if [ -f $SYSENV_CF ]
    then
       grep -vi "^[^#]*_proxy=" $SYSENV_CF > $TEMPFILE
       mv $TEMPFILE $SYSENV_CF
       echo "    Logout and back or restart system may be required"
    fi
    ;;
  check*)
    if [ ! -f $SYSENV_CF ]
    then SYSENV_CHECK="Not Found"
    elif [ $( grep -ci "^[^#]*_proxy=." $SYSENV_CF 2>/dev/null ) -eq 0 ]
       then SYSENV_CHECK=Off
       else SYSENV_CHECK=On
    fi   
    
    echo Sys Environment: $SYSENV_CHECK

    #set -vx
    #SESMGRPID=$(ps -e -o pid,cmd |grep "[s]ession" |awk '{print $1}')
    #[ ! -f /proc/$SESMGRPID/environ ] && RUNNINGSESS="Not Running" || RUNNINGSESS=$(strings /proc/$SESMGRPID/environ |grep -ci _proxy)

    #SYSENV_CHECK=$(grep -ci http.*_proxy= $SYSENV_CONFIG 2>/dev/null) || SYSENV_CHECK=None
    #echo Session Manager Environment: $SYSENV_CHECK \( Active Env=$RUNNINGSESS \)
    #set +vx
    ;;
esac
