#!/bin/bash
# ProxyManager module to set System proxy using /etc/sysconfig/proxy (Eg Suse)
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# Note: Existing processes needs to be restarted for this setting be used
# It is generally required to log out and back in for this setting to take effect.

# Run with root priv to affect Global System Configuration

SUSE_CF=/etc/sysconfig/proxy
. /etc/proxymanager.conf

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile suse-sys

case "$1" in
  on)
    echo Enabling for Suse
    [ -f $SUSE_CF ] || exit
    sed '/ENABLED/ s/"no"/"yes"/' <$SUSE_CF > $TEMPFILE
    mv $TEMPFILE $SUSE_CF
    echo "    Logout and back or reboot may be required"
    ;;
  off)
    echo Disabling for Suse
    [ -f $SUSE_CF ] || exit
    sed '/ENABLED/ s/"yes"/"no"/' <$SUSE_CF > $TEMPFILE
    mv $TEMPFILE $SUSE_CF
    echo "    Logout and back or reboot may be required"
    ;;
  check)
    if [ ! -f $SUSE_CF ]
    then SUSE_CHECK="Not Found"
    elif [ $( grep -c "ENABLED=.*yes" $SUSE_CF 2>/dev/null ) -eq 0 ]
       then SUSE_CHECK=Off
       else SUSE_CHECK=On
    fi
    echo Suse-System: $SUSE_CHECK  
    ;;
esac

