#!/bin/sh
# ProxyManager Module for VirtualBox GUI Proxy setting management
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# VirtualBox uses this for checking for and downloading updates.  This does not
# affect VirtualBox networking in any way.

TEMPFILE=/tmp/pon.virtualbox

. $PM_INSTALL_DIR/modules/.sharedfunctions

case "$1" in
  on)
    echo Enaling for VirtualBox
    ParseTemplate $PM_INSTALL_DIR/templates/enable_virtualbox > $TEMPFILE
    VBoxManage setextradata global GUI/ProxySettings $(cat $TEMPFILE)
    ;;
  off)
    echo Disabling for VirtualBox
    VBoxManage setextradata global GUI/ProxySettings "proxyDisabled,,,authDisabled,,"
    ;;

  check)
    VBOX_CHECK=$(VBoxManage getextradata global GUI/ProxySettings|grep -c "proxyEnabled,..*,..*")
    echo VirtualBox: $VBOX_CHECK
    ;;
esac
