#!/bin/sh
# ProxyManager Module for VirtualBox GUI Proxy setting management
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# VirtualBox uses this for checking for and downloading updates.  This does not
# affect VirtualBox networking in any way.

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile virtualbox

case "$1" in
  on)
    echo Enabling for VirtualBox
    ParseTemplate $PM_INSTALL_DIR/templates/enable_virtualbox > $TEMPFILE
    which VBoxManage > /dev/null && VBoxManage setextradata global GUI/ProxySettings $(cat $TEMPFILE)
    ;;
  off)
    echo Disabling for VirtualBox
    which VBoxManage > /dev/null && VBoxManage setextradata global GUI/ProxySettings "proxyDisabled,,,authDisabled,,"
    ;;

  check*)
    if ! which VBoxManage > /dev/null
    then VBOX_CHECK="Not Found"
    elif [ $( VBoxManage getextradata global GUI/ProxySettings|grep -c "proxyEnabled,..*,..*" ) -eq 0 ]
       then VBOX_CHECK=Off
       else VBOX_CHECK=On
    fi
    ## VBOX_CHECK=$(VBoxManage getextradata global GUI/ProxySettings|grep -c "proxyEnabled,..*,..*")
    echo VirtualBox: $VBOX_CHECK
    ;;
esac
