#!/bin/sh
# ProxyManager module for VideoLAN (vlc) client
# This file is part of ProxyManager
# Copyright 2014 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

# You need to restart any already running VLC instances.

VLC_CF=$PM_USERHOME/.config/vlc/vlcrc

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile vlc

case "$1" in
  on)
    echo Enabling for VLC
    grep -v "^http-proxy.* =" $VLC_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/enable_vlc >> $TEMPFILE
    cp $TEMPFILE $VLC_CF
    pgrep -U ${PM_USERNAME} vlc >/dev/null && echo "   Restart VideoLAN/VLC client for changed setting to take effect"
    ;;
  off)
    echo Disabling for VLC
    grep -v "^http-proxy.*=" $VLC_CF > $TEMPFILE
    cat $PM_INSTALL_DIR/templates/disable_vlc >> $TEMPFILE
    cp $TEMPFILE $VLC_CF
    pgrep -U ${PM_USERNAME} vlc >/dev/null && echo "   Restart VideoLAN/VLC client for changed setting to take effect"
    ;;
  check*)
    if [ ! -f $VLC_CF ]
    then VLC_CHECK="Not Found"
    elif [ $( grep -c "^http-proxy.*=.*[a-z]" $VLC_CF 2>/dev/null ) -eq 0 ]
      then VLC_CHECK=Off
      else VLC_CHECK=On
    fi
    echo VLC: $VLC_CHECK
    ;;
esac
