#!/bin/bash
# ProxyManager module for Wget
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

WGET_CF=$PM_USERHOME/.wgetrc
TEMPFILE=/tmp/pon.wgetrc
[ -f $TEMPFILE ] && ( rm $TEMPFILE || exit 3 )

case "$1" in
  on)
    echo Enabling for wget
    [ -f $WGET_CF ] && grep -v "^[^#].*_proxy" $WGET_CF > $TEMPFILE
    cat $PM_INSTALL_DIR/templates/enable_wgetrc >> $TEMPFILE
    mv $TEMPFILE $WGET_CF
    ;;
  off)
    echo Disabling for wget
    grep -v "^[^#].*_proxy" $WGET_CF > $TEMPFILE
    mv $TEMPFILE $WGET_CF
    ;;
  check)
    WGET_CHECK=$(grep -c http.*proxy $WGET_CF 2>/dev/null) || WGET_CHECK=None
    echo Wget: $WGET_CHECK
    ;;
esac
