#!/bin/bash
# ProxyManager module for Wget
# This file is part of ProxyManager
# Copyright 2013 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See the included README file for contact and additional information
# See the included COPYING file for licensing information

WGET_CF=$PM_USERHOME/.wgetrc

. $PM_INSTALL_DIR/modules/.sharedfunctions
GetUniqueTempFile wgetrc

case "$1" in
  on)
    echo Enabling for wget
    [ -f $WGET_CF ] && grep -v "^[^#]*_proxy" $WGET_CF > $TEMPFILE
    ParseTemplate $PM_INSTALL_DIR/templates/enable_wgetrc >> $TEMPFILE
    mv $TEMPFILE $WGET_CF
    ;;
  off)
    echo Disabling for wget
    grep -v "^[^#]*_proxy" $WGET_CF > $TEMPFILE
    mv $TEMPFILE $WGET_CF
    ;;
  check)
    if [ ! -f $WGET_CF ]
    then WGET_CHECK="Not Found"
    elif [ $( grep -c "^[^#]*_proxy" $WGET_CF 2>/dev/null ) -eq 0 ]
      then WGET_CHECK=Off
      else WGET_CHECK=On
    fi
    echo Wget: $WGET_CHECK
    ;;
esac
