#!/bin/bash

# This file is part of ProxyManager
# Copyright 2014 Johan Hartzenberg 
# ProxyManager is distributed under the terms of the GNU General Public License
# See README file for contact and additional information and COPYING for license

# This utility will create or update the ProxyManager configuration file and prompt to enable/disable included modules.

[ -f /etc/proxymanager.conf ] && . /etc/proxymanager.conf

DEFAULTDIR=${PM_INSTALL_DIR:-/usr/local/proxymanager}
printf "Enter install dir: [$DEFAULTDIR] : "
read SPECIFIED_DIR
NEW_INSTALL_DIR="${SPECIFIED_DIR:-$DEFAULTDIR}"

if [ ! -x "$NEW_INSTALL_DIR/proxymanager" ]
then
   echo '  ERROR: proxymanager not found at "'$NEW_INSTALL_DIR/proxymanager'" - aborting!'
   exit 2
fi

DEFAULTHOST=${PM_PROXY_HOST:-localhost}
printf "Enter Proxy Server [$DEFAULTHOST]: "
read SPECIFIED_HOST
NEW_HOST=${SPECIFIED_HOST:-$DEFAULTHOST}

DEFAULTPORT=${PM_PROXY_PORT:-3128}
printf "Enter Proxy Port [$DEFAULTPORT]: "
read SPECIFIED_PORT
NEW_PORT=${SPECIFIED_PORT:-$DEFAULTPORT}

cat <<CONFEND > /etc/proxymanager.conf
# ProxyManager configuration created via the proxymanager-setup script
# See sample-proxymanager.conf for a description of this file.
PM_INSTALL_DIR=$NEW_INSTALL_DIR
PM_USERNAME=\${SUDO_USER:-\$USER}
PM_USERHOME=\`eval echo ~\$PM_USERNAME\`
PM_PROXY_HOST=$NEW_HOST
PM_PROXY_PORT=$NEW_PORT
# unset PM_USERMODULES
CONFEND

printf "Update Active Modules list now y/N: "
read UPDATENOW
case "$UPDATENOW" in
  y|Y|yes|Yes|YES)
     $NEW_INSTALL_DIR/proxymanager-module avail
     cd $NEW_INSTALL_DIR/modules
     for MODULE in $( ls )
     do
        printf "Module \"$MODULE\" ? Enable / [Disable] : "
        read CONFIRM
        case $CONFIRM in
           e|E|enable|Enable|ENABLE)
               $NEW_INSTALL_DIR/proxymanager-module enable $MODULE
               echo Enabled
               ;;
           *)
               $NEW_INSTALL_DIR/proxymanager-module disable $MODULE
               echo Disabled.
        esac
     done
     ;;
esac

cat <<ALIAS_NOTE

$NEW_INSTALL_DIR/proxymanager-module list
Copy-paste these alias definitions to your Shell profile (eg .bashrc)
#--- Cut below this line ---
alias p-on="'$NEW_INSTALL_DIR'/proxymanager on"
alias p-off="'$NEW_INSTALL_DIR'/proxymanager off"
alias p-check="'$NEW_INSTALL_DIR'/proxymanager check"
#--- Cut above this line ---
ALIAS_NOTE
